### ISSUE TITLE
Destination folder

### ISSUE THREAD

**Issue by if-alice** [ati/ljsm#10]
Здравствуйте, не могли бы ли вы подсказать, в какую папку сохраняется блог?

**Comment by ati** [comment]
Здравствуйте, в папку с именем, равным имени юзера, чей бэкап вы делаете.

**Comment by if-alice** [comment]
А эта папка должна находиться в той папке, из которой запущен скрипт?

**Comment by ati** [comment]
Да, в той папке, откуда запущен (а не лежит сам файл) скрипта.

**Comment by if-alice** [comment]
Спасибо
