### ISSUE TITLE
Спецсимволы в пароле

### ISSUE THREAD

**Issue by s-tikhomirov** [ati/ljsm#8]
Возникает ошибка при попытке скачивания ЖЖ с паролем, содержащим восклицательный знак. Символы ` и " в пароле вызывают командную строку.

**Comment by ati** [comment]
Это не ошибка ljsm, это штатное поведение вашего shell-a. 
см. например http://mywiki.wooledge.org/BashGuide/SpecialCharacters

**Comment by s-tikhomirov** [comment]
@ati Это-то понятно, но как быть пользователю ljsm, у которого правильный пароль на ЖЖ со спецсимволами? Понятно, что можно поменять пароль, но это too much of a hack, IMO.

**Comment by ati** [comment]
экранировать в соответствии с правилами вашего shell-a.
если в пароле нет одиночных кавычек, то проще всего заключить пару юзернейм:пароль в одиночные кавычки.
Если одиночные кавычки есть - экранировать их бэкслэшами. И т.д.
https://askubuntu.com/questions/644092/bash-script-and-escaping-special-characters-in-password
